# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todolist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etodolist.proto\x12\tprotoblog\"\xb0\x01\n\x08TodoList\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\x12\x12\n\nowner_name\x18\x02 \x01(\t\x12,\n\x05todos\x18\x03 \x03(\x0b\x32\x1d.protoblog.TodoList.ListItems\x1aP\n\tListItems\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.protoblog.TaskState\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x10\n\x08\x64ue_date\x18\x03 \x01(\t*e\n\tTaskState\x12\r\n\tTASK_OPEN\x10\x00\x12\x14\n\x10TASK_IN_PROGRESS\x10\x01\x12\x13\n\x0fTASK_POST_PONED\x10\x02\x12\x0f\n\x0bTASK_CLOSED\x10\x03\x12\r\n\tTASK_DONE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'todolist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSTATE']._serialized_start=208
  _globals['_TASKSTATE']._serialized_end=309
  _globals['_TODOLIST']._serialized_start=30
  _globals['_TODOLIST']._serialized_end=206
  _globals['_TODOLIST_LISTITEMS']._serialized_start=126
  _globals['_TODOLIST_LISTITEMS']._serialized_end=206
# @@protoc_insertion_point(module_scope)
